import type { Agent, RunOptions } from './contracts.js'
import type { SessionRuntime } from './session-runtime.js'
import type { SystemPromptRuntime } from './system-prompt-runtime.js'
import type { ToolRuntime } from './tool-runtime.js'
import type { LlmRuntime } from './llm-runtime.js'
const CANCELLED_RESULT = 'ToolError: the run was cancelled before this tool ran'

export class AgentLoopRuntime {
    sessions: Pick<SessionRuntime, "append" | "deriveMessages">
    systemPrompt: Pick<SystemPromptRuntime, "assemble">
    tools: Pick<ToolRuntime, "schemas" | "execute" | "renderResult">
    llm: Pick<LlmRuntime, "chat">
    constructor({ sessions, systemPrompt, tools, llm }: { sessions: Pick<SessionRuntime, "append" | "deriveMessages">; systemPrompt: Pick<SystemPromptRuntime, "assemble">; tools: Pick<ToolRuntime, "schemas" | "execute" | "renderResult">; llm: Pick<LlmRuntime, "chat"> }) {
        this.sessions = sessions
        this.systemPrompt = systemPrompt
        this.tools = tools
        this.llm = llm
    }

    async run(agent: Agent, input: string, { signal, onReasoning, onContent, onToolCall, onToolResult }: RunOptions = {}) {
        const sessionId = agent.sessionId

        this.sessions.append(sessionId, 'user/message', { content: input })
        //step1: Append the user's input message to the session's event log, marking the start of the agent's reasoning process

        let step = 0

        while (true) {
            step += 1

            if (signal?.aborted) {
                throw new Error('Agent run cancelled')
            }

            const system = await this.systemPrompt.assemble({
                agent,
                sessionId,
                step,
            })
            //step2: Assemble the system prompt based on the current agent, session ID, and step number. This prompt will guide the agent's reasoning and decision-making process.

            const messages = this.sessions.deriveMessages(sessionId)

            const response = await this.llm.chat(
                {
                    system,
                    messages,
                    tools: this.tools.schemas(),
                    signal,
                    onReasoning,
                    onContent,
                },
                agent.model,
            )
            //step3: Use the LLM to generate a response based on the system prompt, the derived messages, available tools, and any provided callbacks for reasoning and content. The model used is specified by the agent's model selection.

            const toolCalls = response.toolCalls ?? []

            if (toolCalls.length === 0) {
                const content = response.content ?? ''
                this.sessions.append(sessionId, 'assistant/message', { content })
                return content
            }//step4: If the LLM's response does not include any tool calls, append the assistant's message to the session and return the content. This indicates that the agent has completed its reasoning without needing to invoke any tools.

            this.sessions.append(sessionId, 'assistant/tool_calls', {
                content: response.content ?? null,
                reasoningContent: response.reasoningContent,
                toolCalls,
            })

            let cancelled = false

            for (const call of toolCalls) {
                cancelled ||= Boolean(signal?.aborted)

                if (cancelled) {
                    this.sessions.append(sessionId, 'tool/result', {
                        toolCallId: call.id,
                        name: call.name,
                        isError: true,
                        content: CANCELLED_RESULT,
                    })
                    continue
                }

                onToolCall?.(call)

                const result = await this.tools.execute(call.name, call.arguments, {
                    signal,
                    sessionId,
                    toolCallId: call.id,
                    agent,
                })//step5: For each tool call generated by the LLM, check if the run has been cancelled. If not, invoke the corresponding tool with the provided arguments and execution context. Capture the result of the tool execution, which may include success or error information.

                const renderedContent = this.tools.renderResult(result)
                onToolResult?.({ ...result, renderedContent, name: call.name, toolCallId: call.id })

                this.sessions.append(sessionId, 'tool/result', {
                    toolCallId: call.id,
                    name: call.name,
                    isError: result.isError,
                    content: renderedContent,
                })
            }
            //step6: After executing each tool, render the result for display, invoke any provided callbacks for tool results, and append the tool's result to the session's event log. This allows the agent to continue its reasoning based on the outcomes of the tool executions.

            if (cancelled) {
                throw new Error('Agent run cancelled')
            }

        }
    }
}